Debug script

diff --git a/pipeline/steps/build-wheel.yaml b/pipeline/steps/build-wheel.yaml
--- a/pipeline/steps/build-wheel.yaml
+++ b/pipeline/steps/build-wheel.yaml
@@ -41,20 +41,34 @@ steps:
     scriptType: bash
     scriptLocation: inlineScript
     inlineScript: |
+      echo "Installing required tools..."
       pip install --upgrade pip build
-      ls $(System.DefaultWorkingDirectory)/${{ parameters.mainRepositoryName }}
+      
+      echo "Current directory: $(System.DefaultWorkingDirectory)/${{ parameters.mainRepositoryName }}/Databricks/SharedFunctionsLib"
+      ls -la $(System.DefaultWorkingDirectory)/${{ parameters.mainRepositoryName }}/Databricks/SharedFunctionsLib
+
+      echo "Building the Python wheel..."
       python${{ parameters.pythonVersion }} -m build --wheel
+
+      echo "Contents of the dist directory after build:"
+      ls $(System.DefaultWorkingDirectory)/${{ parameters.mainRepositoryName }}/Databricks/SharedFunctionsLib/dist || echo "No dist directory found."
+
+      echo "Moving wheel from temporary directories to dist if necessary..."
       mkdir -p $(Pipeline.Workspace)/wheel-cache
-      cp dist/*.whl $(Pipeline.Workspace)/wheel-cache/
-      if [ -f $(Pipeline.Workspace)/wheel-cache/common_functions-*.whl ]; then
+      find $(System.DefaultWorkingDirectory)/${{ parameters.mainRepositoryName }}/Databricks/SharedFunctionsLib/dist/ -name '*.whl' -exec cp {} $(Pipeline.Workspace)/wheel-cache/ \;
+
+      echo "Checking for wheels in wheel-cache..."
+      if ls $(Pipeline.Workspace)/wheel-cache/*.whl 1> /dev/null 2>&1; then
           echo "Preparing wheel for artifact storage..."
-          cp $(Pipeline.Workspace)/wheel-cache/common_functions-*.whl dist/
+          cp $(Pipeline.Workspace)/wheel-cache/*.whl $(System.DefaultWorkingDirectory)/${{ parameters.mainRepositoryName }}/Databricks/SharedFunctionsLib/dist/
       else
           echo "No wheel found to publish."
       fi
+
+      echo "Final contents of the dist directory:"
+      ls $(System.DefaultWorkingDirectory)/${{ parameters.mainRepositoryName }}/Databricks/SharedFunctionsLib/dist || echo "No dist directory found."
     workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.mainRepositoryName }}/Databricks/SharedFunctionsLib'
 
-- publish: dist
-#  condition: eq(variables.shouldBuildWheel, 'true')
+- publish: '$(System.DefaultWorkingDirectory)/${{ parameters.mainRepositoryName }}/Databricks/SharedFunctionsLib/dist'
   artifact: python-wheel
   displayName: 'Publish Python Wheel to Artifact Storage'
